baseURL = "https://3ar0n.github.io/"
title = "Thái Đặng"
theme = "m10c"
paginate = 5

[params]
  author = "Đặng Quốc Thái"
  description = "walk on my own way"
  [[params.social]]
    name = "github"
    url = "https://github.com/3ar0n"
  [[params.social]]
    name = "facebook"
    url = "https://www.facebook.com/dangquocthai316"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
