baseURL = "https://3ar0n.github.io/"
languageCode = "en-us"
title = "Thái Đặng"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    description = "Personal blog"
    githubUsername = "3ar0n"
    accent = "#00AEFF"
    showBorder = true
    backgroundColor = "GhostWhite"
    font = "Nunito" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/"
    name = "About"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:thaidq2@vng.com.vn"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/3ar0n/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://facebook.com/dangquocthai316/"
    name = "facebook"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/thái-đặng-885796135/"
    name = "linkedin"
    weight = 4
